//! Unit tests for the behavioral-coverage primitives.
//!
//! Frozen at Red per the Red-Green-Replay section of
//! `SPECIFICATION/non-functional-requirements.md`. The gap-id parity vectors in
//! `tests/data/parity_golden.json` are generated from the family's vendored
//! `spec_clauses.py` primitive (the exact module the orchestrator's
//! `detect-impl-gaps` vendors), so the Rust port's gap-ids are pinned
//! byte-for-byte to the family primitive. `tests/data/parity_fixture.md` is
//! the shared input both sides extract from.

use super::{
    Audience, ClauseLink, CoverageEntry, CoverageReport, Mode, NFR_FILE, SpecSource,
    UnlinkedClause, UntestedScenario, contains_whole_word, derive_gap_id, evaluate, extract_rules,
    nfr_scenarios, normalize_scenario, operator_scenarios, parse_heading, parse_registry,
    push_heading, resolve_mode,
};

const FIXTURE: &str = include_str!("../tests/data/parity_fixture.md");
const GOLDEN: &str = include_str!("../tests/data/parity_golden.json");

#[test]
fn gap_id_parity_with_vendored_python_primitive() -> Result<(), Box<dyn std::error::Error>> {
    let golden: serde_json::Value = serde_json::from_str(GOLDEN)?;
    let golden = golden.as_array().ok_or("golden is not a JSON array")?;
    let rules = extract_rules("parity_fixture.md", FIXTURE);
    assert_eq!(rules.len(), golden.len(), "rule count vs golden");
    for (rule, want) in rules.iter().zip(golden.iter()) {
        let want = want.as_object().ok_or("golden entry is not an object")?;
        let field = |key: &str| want.get(key).and_then(serde_json::Value::as_str);
        assert_eq!(Some(rule.spec_file.as_str()), field("spec_file"));
        assert_eq!(Some(rule.heading_path.as_str()), field("heading_path"));
        assert_eq!(Some(rule.line_text.as_str()), field("line_text"));
        assert_eq!(
            Some(rule.gap_id.as_str()),
            field("gap_id"),
            "gap-id for {:?}",
            rule.line_text
        );
    }
    Ok(())
}

#[test]
fn derive_gap_id_matches_python_known_vectors() {
    // Generated by the vendored `spec_clauses.derive_gap_id` over the fixture.
    assert_eq!(
        derive_gap_id(
            "parity_fixture.md",
            "(top)",
            "Intro: the runtime MUST boot before any heading is seen.",
        ),
        "gap-p5qdeqai",
    );
    assert_eq!(
        derive_gap_id(
            "parity_fixture.md",
            "Delta >  > Epsilon",
            "A padded clause that MUST appear with an empty middle crumb.",
        ),
        "gap-nvq2jmqr",
    );
}

#[test]
fn extract_rules_matches_real_spec_ground_truth() -> Result<(), Box<dyn std::error::Error>> {
    // Ground truth measured via the family `spec_clauses.py` over the console
    // SPECIFICATION. Updated for the v018 persistence-seam revision, which
    // dropped one normative clause from contracts.md (the console's own
    // autonomous-mode persistence clause) in favor of the orchestrator's single
    // permission key: 122 normative clauses, 15/36/19/52. The S1 resolver
    // revision added one contracts.md clause for validated orchestrator-plugin
    // backing CLI resolution: 123 normative clauses, 15/37/19/52. The S2
    // source-unavailability indicator added one contracts.md TUI-Contract clause
    // requiring the header/status line to surface backing-source unavailability:
    // 124 normative clauses, 15/38/19/52. The S4b valve-keys slice added one
    // contracts.md TUI-Contract clause requiring the operator to drive all five
    // human-valve/policy-edit commands from the TUI through the shared
    // orchestrator action port, with a confirmed destructive reject:
    // 125 normative clauses, 15/39/19/52. The W2 dispatcher-settings re-baseline
    // retired the Full Autonomous Mode / Autonomous Mode / Autonomous-Mode Safety
    // sections and replaced them with the six-setting Dispatcher Policy Settings
    // surface, its per-item override valve, the factory-drain launcher argv (no
    // per-run policy-arming argument), and the consumer-side completeness check;
    // it also grew the Work-item Lifecycle vocabulary from five commands to six.
    // spec.md nets unchanged at 15 (the retired section's 12 clauses give way to
    // 12: 11 re-expressed plus the new drain sentence):
    // 146 normative clauses, 15/57/22/52. (The v017 C1 revision net-added one
    // normative clause each to spec.md and constraints.md as the autonomous
    // sections were re-scoped to the delegation model; the v016 CN1 revision added
    // one normative clause to contracts.md; the earlier v014 console-cruft-cleanup
    // revision added four.)
    // The B4 pane-specific modal Help revision added seven contracts.md
    // TUI-Contract clauses (the navigable, context-specific `?`-invoked modal
    // overlay: a near-full-viewport 3-character-border window never wider than the
    // viewport, a left-side section menu beside an up/down-only-scrolling right
    // pane, a Global-actions section plus one per focusable pane with per-pane
    // auto-focus, and Esc-only dismissal with `esc to exit` always shown), and the
    // B1 source-availability-honesty revision added six contracts.md Adapter-
    // Contract clauses (a reachable-but-empty source is observed-and-idle not
    // unavailable, a not-observed finding carries a durably-persisted human-
    // readable reason, and the header tally reflects the latest poll outcome per
    // source so a recovered source clears): 159 normative clauses, 15/70/22/52.
    // The B2 status-line-context-hints revision added one contracts.md
    // TUI-Contract clause requiring the Status line to render context-specific,
    // non-empty shortcut key hints that reflect the focused pane and change when
    // focus moves or a modal/overlay opens or closes: 160 normative clauses,
    // 15/71/22/52.
    // The B3 top-pane-focus-hscroll revision added one contracts.md
    // TUI-Contract clause requiring the top/header pane to join the pane focus
    // cycle, scroll horizontally to reveal content clipped at the current
    // viewport width while focused, and snap back to its left-justified default
    // on blur: 161 normative clauses, 15/72/22/52.
    // The B5 panes-no-doc-prose revision added one contracts.md
    // TUI-Contract clause requiring the panes to render operational content
    // only -- the live data and state an operator acts on -- and never carry
    // baked-in explanatory or documentation prose describing what the console
    // is, how a projection is derived, or how a view behaves, beyond the
    // required operational help surfaces (the Status-line hints, the modal
    // Help overlay, and the Settings per-row inline help): 162 normative
    // clauses, 15/73/22/52.
    // The B6 user-docs-tree revision added three contracts.md clauses under a
    // new User-Documentation-Contract section: user-facing documentation lives
    // under a `docs/` tree with the top-level README carrying no user-facing
    // documentation of its own and `docs/README.md` an overview plus a
    // relative-path table of contents; the tree covers installation, overview
    // and quick start, environment variables / CLI options / sub-commands, and
    // detailed usage with a section per TUI pane; and the settings doc the
    // completeness check reads is the detailed-usage sub-document rather than
    // the top-level README. The Settings-surface-completeness re-anchor
    // re-worded an existing clause without changing the count. The work-item
    // record drill-in then ADDED one contracts.md clause (the operator reads a
    // selected work-item's full standardized record without leaving the
    // console) and re-worded the Status-line clause in place: 166 normative
    // clauses, 15/77/22/52. The command-queue single-consumer revision added
    // eight contracts.md clauses for pending -> executing claims, duplicate
    // consumer no-ops, terminal finalization, and stale executing recovery:
    // 174 normative clauses, 15/85/22/52.
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../SPECIFICATION");
    let cases = [
        ("spec.md", 15_usize),
        ("contracts.md", 85),
        ("constraints.md", 22),
        ("non-functional-requirements.md", 52),
    ];
    let mut total = 0;
    for (file, want) in cases {
        let text = std::fs::read_to_string(format!("{root}/{file}"))?;
        let count = extract_rules(file, &text).len();
        assert_eq!(count, want, "clause count for {file}");
        total += count;
    }
    assert_eq!(
        total, 174,
        "total normative clauses across the console spec"
    );
    Ok(())
}

#[test]
fn parse_heading_matches_python_regex() {
    assert_eq!(parse_heading("# Alpha"), Some((1, "Alpha".to_string())));
    assert_eq!(parse_heading("## Beta"), Some((2, "Beta".to_string())));
    assert_eq!(parse_heading("###### Six"), Some((6, "Six".to_string())));
    assert_eq!(
        parse_heading("##   Padded  "),
        Some((2, "Padded".to_string()))
    );
    assert_eq!(
        parse_heading("####### Seven"),
        None,
        "seven hashes is not a heading"
    );
    assert_eq!(
        parse_heading("#nospace"),
        None,
        "no whitespace after hashes"
    );
    assert_eq!(parse_heading("## "), None, "empty title");
    assert_eq!(parse_heading("plain text"), None);
    assert_eq!(parse_heading(""), None);
}

#[test]
fn push_heading_pops_and_pads() {
    let mut stack = vec!["A".to_string(), "B".to_string()];
    push_heading(&mut stack, 1, "C".to_string());
    assert_eq!(stack, vec!["C".to_string()]);
    push_heading(&mut stack, 3, "E".to_string());
    assert_eq!(stack, vec!["C".to_string(), String::new(), "E".to_string()]);
    push_heading(&mut stack, 2, "F".to_string());
    assert_eq!(stack, vec!["C".to_string(), "F".to_string()]);
}

#[test]
fn contains_whole_word_respects_unicode_boundaries() {
    assert!(contains_whole_word("MUST", "MUST"), "whole string");
    assert!(contains_whole_word("a MUST b", "MUST"), "spaces");
    assert!(contains_whole_word("see `MUST` here", "MUST"), "backticks");
    assert!(
        contains_whole_word("a MUST.", "MUST"),
        "trailing punctuation"
    );
    assert!(!contains_whole_word("MUSTARD", "MUST"), "word char after");
    assert!(!contains_whole_word("aMUST", "MUST"), "word char before");
    assert!(!contains_whole_word("MUST_", "MUST"), "underscore after");
    assert!(
        !contains_whole_word("trust", "MUST"),
        "absent (case sensitive)"
    );
    assert!(
        contains_whole_word("aMUST MUST", "MUST"),
        "skip bad occurrence, find good one"
    );
}

#[test]
fn normalize_scenario_strips_hashes_and_whitespace() {
    assert_eq!(normalize_scenario("## Scenario 1 -- A"), "Scenario 1 -- A");
    assert_eq!(normalize_scenario("Scenario 2 -- B"), "Scenario 2 -- B");
    assert_eq!(normalize_scenario("   ##   Padded  "), "Padded");
    assert_eq!(normalize_scenario("####"), "");
}

#[test]
fn operator_scenarios_collects_only_h2_headings() {
    let md = "# scenarios\n\n## Scenario 1 -- A\n\ntext MUST x\n\n### sub\n\n## Scenario 2 -- B\n";
    assert_eq!(
        operator_scenarios(md),
        vec!["Scenario 1 -- A".to_string(), "Scenario 2 -- B".to_string()],
    );
}

#[test]
fn nfr_scenarios_collects_h2s_after_the_marker() {
    let with =
        "## Boundary\n\n## Contracts\n\n## Scenarios\n\n## Theme One\n\ngherkin\n\n## Theme Two\n";
    assert_eq!(
        nfr_scenarios(with),
        vec!["Theme One".to_string(), "Theme Two".to_string()]
    );

    let empty = "## Boundary\n\n## Scenarios\n\nNo contributor-facing scenarios are pinned yet.\n";
    assert_eq!(nfr_scenarios(empty), Vec::<String>::new());

    let no_marker = "## Boundary\n\n## Contracts\n";
    assert_eq!(nfr_scenarios(no_marker), Vec::<String>::new());
}

#[test]
fn parse_registry_reads_entries_and_defaults_clauses() -> Result<(), String> {
    let json = r#"[
      {"scenario":"S1","scenario_file":"scenarios.md","test":"t::a",
       "reason":"covered by a top-of-pyramid test",
       "clauses":[{"gap_id":"gap-1","scenario":"S1"}]},
      {"scenario":"S2","scenario_file":"scenarios.md","test":"t::b"}
    ]"#;
    let entries = parse_registry(json)?;
    assert_eq!(entries.len(), 2);
    assert_eq!(entries[0].reason, "covered by a top-of-pyramid test");
    assert_eq!(entries[1].reason, "", "missing reason defaults to empty");
    assert_eq!(
        entries[0].clauses,
        vec![ClauseLink {
            gap_id: "gap-1".to_string(),
            scenario: "S1".to_string()
        }],
    );
    assert_eq!(entries[1].clauses, Vec::new());
    Ok(())
}

#[test]
fn parse_registry_rejects_non_array_and_bad_json() {
    assert!(parse_registry("not json").is_err());
    assert!(parse_registry("{}").is_err());
}

#[test]
fn parse_registry_skips_malformed_entries() -> Result<(), String> {
    let json = r#"[
      42,
      {"scenario_file":"scenarios.md","test":"t"},
      {"scenario":"NoFile","test":"t"},
      {"scenario":"OK","scenario_file":"scenarios.md","test":"t",
       "clauses":[5,{"gap_id":"g"},{"gap_id":"g2","scenario":"X"}]},
      {"scenario":"NoTestField","scenario_file":"scenarios.md","clauses":7}
    ]"#;
    let entries = parse_registry(json)?;
    assert_eq!(
        entries.len(),
        2,
        "non-object and field-missing entries are skipped"
    );
    assert_eq!(entries[0].scenario, "OK");
    assert_eq!(
        entries[0].clauses,
        vec![ClauseLink {
            gap_id: "g2".to_string(),
            scenario: "X".to_string()
        }],
    );
    assert_eq!(entries[1].scenario, "NoTestField");
    assert_eq!(entries[1].test, "", "missing test field defaults to empty");
    assert_eq!(
        entries[1].reason, "",
        "missing reason field defaults to empty"
    );
    assert_eq!(
        entries[1].clauses,
        Vec::new(),
        "non-array clauses default to empty"
    );
    Ok(())
}

#[test]
fn evaluate_flags_unlinked_and_resolves_links() {
    // A top-level clause (no heading) keeps the heading_path the predictable
    // "(top)"; an H2 with no preceding H1 would pad a leading empty crumb.
    let spec = "The widget MUST spin.\n";
    let gap = derive_gap_id("spec.md", "(top)", "The widget MUST spin.");
    let sources = [SpecSource {
        spec_file: "spec.md",
        content: spec,
        audience: Audience::Operator,
    }];
    let operator = vec!["Scenario 1 -- A".to_string()];
    let nfr: Vec<String> = Vec::new();

    let report = evaluate(&sources, &[], &operator, &nfr);
    assert_eq!(report.unlinked_clauses.len(), 1, "no registry -> unlinked");
    assert_eq!(report.unlinked_clauses[0].gap_id, gap);

    let linked = vec![CoverageEntry {
        scenario: "Scenario 1 -- A".to_string(),
        scenario_file: "scenarios.md".to_string(),
        test: "t::a".to_string(),
        reason: String::new(),
        clauses: vec![ClauseLink {
            gap_id: gap.clone(),
            scenario: "Scenario 1 -- A".to_string(),
        }],
    }];
    let report = evaluate(&sources, &linked, &operator, &nfr);
    assert!(
        report.unlinked_clauses.is_empty(),
        "linked to a live scenario"
    );
    assert!(
        report.untested_scenarios.is_empty(),
        "scenario now has a test"
    );

    let stale = vec![CoverageEntry {
        scenario: "Ghost".to_string(),
        scenario_file: "scenarios.md".to_string(),
        test: "t".to_string(),
        reason: String::new(),
        clauses: vec![ClauseLink {
            gap_id: gap,
            scenario: "Ghost".to_string(),
        }],
    }];
    assert_eq!(
        evaluate(&sources, &stale, &operator, &nfr)
            .unlinked_clauses
            .len(),
        1,
        "a link to a non-live scenario does not count",
    );
}

#[test]
fn evaluate_partitions_clause_audiences() {
    let nfr_spec = "Contributors MUST lint.\n";
    let gap = derive_gap_id(
        "non-functional-requirements.md",
        "(top)",
        "Contributors MUST lint.",
    );
    let sources = [SpecSource {
        spec_file: "non-functional-requirements.md",
        content: nfr_spec,
        audience: Audience::Contributor,
    }];
    let operator = vec!["Op Scenario".to_string()];
    let nfr = vec!["Nfr Theme".to_string()];

    let wrong = vec![CoverageEntry {
        scenario: "Op Scenario".to_string(),
        scenario_file: "scenarios.md".to_string(),
        test: "t".to_string(),
        reason: String::new(),
        clauses: vec![ClauseLink {
            gap_id: gap.clone(),
            scenario: "Op Scenario".to_string(),
        }],
    }];
    assert_eq!(
        evaluate(&sources, &wrong, &operator, &nfr)
            .unlinked_clauses
            .len(),
        1,
        "a contributor clause linked to an operator scenario is still unlinked",
    );

    let right = vec![CoverageEntry {
        scenario: "Nfr Theme".to_string(),
        scenario_file: NFR_FILE.to_string(),
        test: "t".to_string(),
        reason: String::new(),
        clauses: vec![ClauseLink {
            gap_id: gap,
            scenario: "Nfr Theme".to_string(),
        }],
    }];
    assert!(
        evaluate(&sources, &right, &operator, &nfr)
            .unlinked_clauses
            .is_empty(),
        "linked to the correct-audience NFR scenario",
    );
}

#[test]
fn evaluate_flags_untested_scenarios() {
    let sources: [SpecSource; 0] = [];
    let operator = vec!["Op A".to_string(), "Op B".to_string()];
    let nfr = vec!["Nfr A".to_string()];
    let registry = vec![
        CoverageEntry {
            scenario: "Op A".to_string(),
            scenario_file: "scenarios.md".to_string(),
            test: "t::opa".to_string(),
            reason: String::new(),
            clauses: Vec::new(),
        },
        CoverageEntry {
            scenario: "Op B".to_string(),
            scenario_file: "scenarios.md".to_string(),
            test: "   ".to_string(),
            reason: "ignored for blank tests".to_string(),
            clauses: Vec::new(),
        },
    ];
    let report = evaluate(&sources, &registry, &operator, &nfr);
    let untested: Vec<(&str, &str)> = report
        .untested_scenarios
        .iter()
        .map(|u| (u.scenario_file.as_str(), u.scenario.as_str()))
        .collect();
    assert_eq!(
        untested,
        vec![("scenarios.md", "Op B"), (NFR_FILE, "Nfr A")],
        "whitespace test counts as untested; missing entry counts as untested",
    );
}

#[test]
fn evaluate_accepts_reasoned_pending_todo_scenarios() {
    let sources: [SpecSource; 0] = [];
    let operator = vec!["Pending Op".to_string()];
    let nfr = vec!["Pending Nfr".to_string()];
    let registry = vec![
        CoverageEntry {
            scenario: "Pending Op".to_string(),
            scenario_file: "scenarios.md".to_string(),
            test: "TODO".to_string(),
            reason: "Test tier: a top-of-pyramid acceptance test will cover this scenario."
                .to_string(),
            clauses: Vec::new(),
        },
        CoverageEntry {
            scenario: "Pending Nfr".to_string(),
            scenario_file: NFR_FILE.to_string(),
            test: "TODO".to_string(),
            reason: "Test tier: integration coverage will land with the implementation slice."
                .to_string(),
            clauses: Vec::new(),
        },
    ];

    let report = evaluate(&sources, &registry, &operator, &nfr);
    assert!(
        report.untested_scenarios.is_empty(),
        "reasoned TODO entries are valid pending registrations"
    );
}

#[test]
fn evaluate_rejects_unreasoned_pending_todo_scenarios() {
    let sources: [SpecSource; 0] = [];
    let operator = vec![
        "No Reason".to_string(),
        "No Tier".to_string(),
        "Concrete".to_string(),
    ];
    let nfr: Vec<String> = Vec::new();
    let registry = vec![
        CoverageEntry {
            scenario: "No Reason".to_string(),
            scenario_file: "scenarios.md".to_string(),
            test: "TODO".to_string(),
            reason: "   ".to_string(),
            clauses: Vec::new(),
        },
        CoverageEntry {
            scenario: "No Tier".to_string(),
            scenario_file: "scenarios.md".to_string(),
            test: "TODO".to_string(),
            reason: "Pending until the implementation slice lands.".to_string(),
            clauses: Vec::new(),
        },
        CoverageEntry {
            scenario: "Concrete".to_string(),
            scenario_file: "scenarios.md".to_string(),
            test: "crates/console-cli/tests/concrete.rs::scenario".to_string(),
            reason: String::new(),
            clauses: Vec::new(),
        },
    ];

    let report = evaluate(&sources, &registry, &operator, &nfr);
    let untested: Vec<(&str, &str)> = report
        .untested_scenarios
        .iter()
        .map(|u| (u.scenario_file.as_str(), u.scenario.as_str()))
        .collect();
    assert_eq!(
        untested,
        vec![("scenarios.md", "No Reason"), ("scenarios.md", "No Tier")],
        "TODO entries need both a reason and a scenario-level test-tier acknowledgement",
    );
}

#[test]
fn coverage_report_is_clean_only_when_empty() {
    let clean = CoverageReport {
        unlinked_clauses: Vec::new(),
        untested_scenarios: Vec::new(),
    };
    assert!(clean.is_clean());

    let with_unlinked = CoverageReport {
        unlinked_clauses: vec![UnlinkedClause {
            spec_file: "f".to_string(),
            heading_path: "h".to_string(),
            gap_id: "g".to_string(),
            clause: "c".to_string(),
        }],
        untested_scenarios: Vec::new(),
    };
    assert!(!with_unlinked.is_clean());

    let with_untested = CoverageReport {
        unlinked_clauses: Vec::new(),
        untested_scenarios: vec![UntestedScenario {
            scenario_file: "f".to_string(),
            scenario: "s".to_string(),
        }],
    };
    assert!(!with_untested.is_clean());
}

#[test]
fn resolve_mode_defaults_to_fail() {
    assert_eq!(resolve_mode(None), Mode::Fail);
    assert_eq!(resolve_mode(Some("fail")), Mode::Fail);
    assert_eq!(resolve_mode(Some("  FAIL  ")), Mode::Fail);
    assert_eq!(resolve_mode(Some("warn")), Mode::Warn);
    assert_eq!(resolve_mode(Some("  WARN  ")), Mode::Warn);
    assert_eq!(resolve_mode(Some("whatever")), Mode::Fail);
}
